# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-27 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PNL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorsubsection',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectorsubsection',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companypnldata',
            name='tlm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PNLyr5', to='DataExtraction.quarter_data'),
        ),
        migrations.AlterField(
            model_name='companypnldata',
            name='y1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PNLyr1', to='DataExtraction.quarter_data'),
        ),
        migrations.AlterField(
            model_name='companypnldata',
            name='y2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PNLyr2', to='DataExtraction.quarter_data'),
        ),
        migrations.AlterField(
            model_name='companypnldata',
            name='y3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PNLyr3', to='DataExtraction.quarter_data'),
        ),
        migrations.AlterField(
            model_name='companypnldata',
            name='y4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PNLyr4', to='DataExtraction.quarter_data'),
        ),
    ]
