# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNL', '0003_auto_20180428_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypnldata',
            name='tlm',
        ),
    ]
