# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNL', '0004_remove_companypnldata_tlm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypnldata',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='companypnldata',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='companypnldata',
            name='q8',
        ),
    ]
