# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.CharField(max_length=2000)),
                ('equivalent', models.CharField(max_length=2000)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssection', models.CharField(max_length=2000)),
                ('equivalent', models.CharField(max_length=2000)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertfindata.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sssection', models.CharField(max_length=2000)),
                ('equivalent', models.CharField(max_length=2000)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertfindata.SubSection')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubSubsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssssection', models.CharField(max_length=2000)),
                ('equivalent', models.CharField(max_length=2000)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertfindata.SubSubSection')),
            ],
        ),
    ]
