# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertfindata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='equivalent',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='equivalent',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='subsubsection',
            name='equivalent',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='subsubsubsection',
            name='equivalent',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
