# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BalanceSheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybalancesheetdata',
            name='s2section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.S2Section'),
        ),
        migrations.AlterField(
            model_name='companybalancesheetdata',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.Section'),
        ),
        migrations.AlterField(
            model_name='companybalancesheetdata',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.SubSection'),
        ),
    ]
