# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-22 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BalanceSheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GbcData',
            new_name='CompanyBalanceSheetData',
        ),
    ]
