# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-22 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BalanceSheet', '0002_auto_20180222_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companybalancesheetdata',
            options={'ordering': ('id',), 'verbose_name': 'Balance Sheet data', 'verbose_name_plural': 'Balance Sheet data'},
        ),
    ]
