# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-13 05:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='team_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('tele_id', models.CharField(max_length=100)),
                ('u_role', models.CharField(blank=True, choices=[('Maker', 'Maker'), ('Lead', 'Lead'), ('Approver', 'Approver')], max_length=200)),
                ('t_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamUser', to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamLead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(max_length=100)),
                ('sector_desctiption', models.CharField(max_length=200)),
                ('team_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.team_list')),
            ],
        ),
    ]
