# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-17 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0002_auto_20180717_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamLead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='team_list',
            name='t_user',
        ),
        migrations.RemoveField(
            model_name='team_list',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='teamlist',
            name='team_lead',
        ),
        migrations.AddField(
            model_name='teamlist',
            name='t_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamlist',
            name='tele_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamlist',
            name='u_role',
            field=models.CharField(blank=True, choices=[('Maker', 'Maker'), ('Lead', 'Lead'), ('Approver', 'Approver')], max_length=200),
        ),
        migrations.AlterField(
            model_name='team_sector',
            name='team_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.TeamList'),
        ),
        migrations.AlterField(
            model_name='teamlist',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.TeamName'),
        ),
        migrations.DeleteModel(
            name='team_list',
        ),
    ]
