# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-17 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20180717_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_sector',
            old_name='sector_desctiption',
            new_name='sector_description',
        ),
    ]
