# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-21 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('ditcode', models.CharField(blank=True, max_length=200, null=True)),
                ('y_end', models.CharField(blank=True, choices=[('December', 'December'), ('March', 'March'), ('June', 'June'), ('September', 'September')], max_length=200)),
                ('c_ticker', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='quarter_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_date', models.CharField(blank=True, max_length=200, null=True)),
                ('q1', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_page', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='S2Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=2000)),
                ('i_synonyms', models.CharField(blank=True, max_length=2000, null=True)),
                ('i_breakdown', models.CharField(blank=True, max_length=5000, null=True)),
                ('i_keyword', models.CharField(blank=True, max_length=1000, null=True)),
                ('i_deduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=2000)),
                ('i_synonyms', models.CharField(blank=True, max_length=400, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=2000)),
                ('i_synonyms', models.CharField(blank=True, max_length=2000, null=True)),
                ('i_breakdown', models.CharField(blank=True, max_length=5000, null=True)),
                ('i_keyword', models.CharField(blank=True, max_length=1000, null=True)),
                ('i_deduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsec_Addition', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsec_Modification', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.Section')),
            ],
        ),
        migrations.CreateModel(
            name='year_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_date', models.CharField(blank=True, max_length=200, null=True)),
                ('y1', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_page', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='s2section',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.SubSection'),
        ),
    ]
