# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-04 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('ditcode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GbcData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.CompanyList')),
            ],
            options={
                'verbose_name_plural': 'Raw data',
                'verbose_name': 'Raw data',
                'ordering': ('subsection', 's2section'),
            },
        ),
        migrations.CreateModel(
            name='quarter_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_date', models.CharField(blank=True, max_length=200, null=True)),
                ('q1', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_page', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='S2Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=2000)),
                ('i_synonyms', models.CharField(blank=True, max_length=2000, null=True)),
                ('i_breakdown', models.CharField(blank=True, max_length=5000, null=True)),
                ('i_keyword', models.CharField(blank=True, max_length=1000, null=True)),
                ('i_deduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=2000)),
                ('i_synonyms', models.CharField(blank=True, max_length=400, null=True)),
                ('i_related', models.CharField(choices=[('Balance Sheet', 'Balance Sheet'), ('Profit and Loss', 'Profit and Loss')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=2000)),
                ('i_synonyms', models.CharField(blank=True, max_length=2000, null=True)),
                ('i_breakdown', models.CharField(blank=True, max_length=5000, null=True)),
                ('i_keyword', models.CharField(blank=True, max_length=1000, null=True)),
                ('i_deduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.Section')),
            ],
        ),
        migrations.CreateModel(
            name='year_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_date', models.CharField(blank=True, max_length=200, null=True)),
                ('y1', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_page', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='s2section',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.SubSection'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='lrq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest_Reporting_Quarter', to='DataExtraction.quarter_data'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='q1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quarter_1', to='DataExtraction.quarter_data'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='q2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quarter_2', to='DataExtraction.quarter_data'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='q3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quarter_3', to='DataExtraction.quarter_data'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='q4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quarter_4', to='DataExtraction.quarter_data'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='s2section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.S2Section'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.Section'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.SubSection'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='tlm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Previous_Year_5', to='DataExtraction.year_data'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='y1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Previous_Year_1', to='DataExtraction.year_data'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='y2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Previous_Year_2', to='DataExtraction.year_data'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='y3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Previous_Year_3', to='DataExtraction.year_data'),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='y4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Previous_Year_4', to='DataExtraction.year_data'),
        ),
    ]
