# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='i_related',
            field=models.CharField(choices=[('Balance Sheet', 'Balance Sheet'), ('Profit and Loss', 'Profit and Loss')], max_length=200),
        ),
    ]
