# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-22 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='created_by',
            new_name='added_by',
        ),
        migrations.AddField(
            model_name='section',
            name='i_related',
            field=models.CharField(choices=[('Balance Sheet', 'Balance Sheet'), ('Profit and Loss', 'Profit and Loss')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
