# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-03 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subsection',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
    ]
