# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-22 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0002_auto_20180222_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SectorDit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dit_name', models.CharField(max_length=1000)),
                ('dit_code', models.CharField(max_length=200)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.Sector')),
            ],
        ),
        migrations.RemoveField(
            model_name='companylist',
            name='ditcode',
        ),
        migrations.AddField(
            model_name='companylist',
            name='ditname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.SectorDit'),
            preserve_default=False,
        ),
    ]
