# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-15 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DataExtraction', '0002_auto_20171204_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbcdata',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GBC_Addition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gbcdata',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GBC_Modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='s2section',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='S2sec_Addition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='s2section',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='S2sec_Modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sec_Addition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sec_Modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsection',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsec_Addition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsection',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsec_Modification', to=settings.AUTH_USER_MODEL),
        ),
    ]
