# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-27 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BalanceSheet', '0003_auto_20180427_1159'),
        ('PNL', '0002_auto_20180427_1159'),
        ('DataExtraction', '0002_auto_20180403_0514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='year_data',
        ),
    ]
