# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-24 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0003_delete_year_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter_data',
            name='company_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.CompanyList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarter_data',
            name='page_extraction',
            field=models.CharField(blank=True, choices=[('bsheet', 'bsheet'), ('pnl', 'pnl')], max_length=200),
        ),
    ]
