# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-22 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0003_auto_20180222_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('India', 'India')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
