# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-22 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0004_companylist_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='copy_main',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sectordit',
            name='copy_Sector',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companylist',
            name='y_end',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=200),
        ),
    ]
