# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-24 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0004_auto_20180524_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter_data',
            name='s2section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.S2Section'),
        ),
        migrations.AddField(
            model_name='quarter_data',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.Section'),
        ),
        migrations.AddField(
            model_name='quarter_data',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.SubSection'),
        ),
    ]
