# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-05 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0005_auto_20180524_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='c_q_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companylist',
            name='c_y_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
