# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-09 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0006_auto_20180705_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_extraction', models.CharField(blank=True, choices=[('bsheet', 'bsheet'), ('pnl', 'pnl')], max_length=200)),
                ('quarter_date', models.CharField(blank=True, max_length=200, null=True)),
                ('q1', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.CompanyList')),
                ('s2section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.S2Section')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.Section')),
                ('subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataExtraction.SubSection')),
            ],
        ),
    ]
