# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-13 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0008_team_list_team_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_list',
            name='t_user',
        ),
        migrations.RemoveField(
            model_name='team_list',
            name='team_lead',
        ),
        migrations.RemoveField(
            model_name='team_sector',
            name='team_user',
        ),
        migrations.DeleteModel(
            name='team_list',
        ),
        migrations.DeleteModel(
            name='Team_Sector',
        ),
    ]
