# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-17 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('DataExtraction', '0009_auto_20180713_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectordit',
            name='team_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Team_Sector'),
        ),
    ]
